### ISSUE TITLE
how to make logout ?

### ISSUE THREAD

**Issue by kzu404** [yemiwebby/laravel-backend-api-twilio#1]
im trying to make logout but not working can you help me ?
```
public function logout(Request $request)
    {
        $request->user()->token()->revoke();
        return response()->json([
            'message' => 'Successfully logged out'
        ]);
    }
```
Error: Call to a member function token() on null in file C:\xampp\htdocs\prototipe\app\Http\Controllers\API\AuthController.php on line 48

**Comment by yemiwebby** [comment]
@kzu404 Please make sure that your logout route is called with the `auth:api` middleware.

`Route::get('logout', 'API\Auth\AuthController')->middleware('auth:api');`

**Comment by kzu404** [comment]
@yemiwebby thank you sir its working now, when i access http://localhost:8000/api/ceo without valid token its showing error "Symfony\Component\Routing\Exception\RouteNotFoundException: Route [login] not defined. in file C:\xampp\htdocs\prototipe\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php on line 420" can i just showing error message like "you need to login first" in json ?

**Comment by kzu404** [comment]
@yemiwebby thank you sir its working now
